[[Task]]
uid = "t001"
name = "task 1"
command = "/usr/bin/notify-send"
args = ["\"this is task 1\""]
timeout = 3000
delay = 200
next = ["t002"]
givestdout = true
readstdin = false

[[Task]]
uid = "t002"
name = "task 2"
command = "/usr/bin/notify-send"
args = ["\"this is task 2\""]
timeout = 3000
delay = 200
next = [""]
givestdout = true
readstdin = false
